// <auto-generated />
using System;
using Ecommerce.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Api.Migrations
{
    [DbContext(typeof(EcommerceDbContext))]
    [Migration("20250811001556_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Socks"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pants"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shirts"
                        });
                });

            modelBuilder.Entity("Ecommerce.Api.Models.LineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("LineItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 8,
                            Quantity = 1,
                            SaleId = 1,
                            UnitPrice = 22.99m
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 6,
                            Quantity = 1,
                            SaleId = 2,
                            UnitPrice = 45.95m
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            Quantity = 1,
                            SaleId = 2,
                            UnitPrice = 15.25m
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 7,
                            Quantity = 1,
                            SaleId = 3,
                            UnitPrice = 34.75m
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 6,
                            Quantity = 1,
                            SaleId = 3,
                            UnitPrice = 45.95m
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 1,
                            Quantity = 1,
                            SaleId = 3,
                            UnitPrice = 75.50m
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 2,
                            Quantity = 2,
                            SaleId = 4,
                            UnitPrice = 53.75m
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 4,
                            Quantity = 2,
                            SaleId = 5,
                            UnitPrice = 10.15m
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 1,
                            Quantity = 1,
                            SaleId = 5,
                            UnitPrice = 75.50m
                        });
                });

            modelBuilder.Entity("Ecommerce.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Hightop Sneakers",
                            Price = 75.50m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Boat Loafers",
                            Price = 53.75m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Dress Socks",
                            Price = 15.25m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Ankle Socks",
                            Price = 10.15m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "Dress Slacks",
                            Price = 35.99m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "Stonewash Jeans",
                            Price = 45.95m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Name = "Flannel Shirt",
                            Price = 34.75m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Name = "Shortsleeve Polo",
                            Price = 22.99m
                        });
                });

            modelBuilder.Entity("Ecommerce.Api.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Sales", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TimeStamp = new DateTime(2025, 8, 1, 12, 37, 22, 0, DateTimeKind.Unspecified),
                            Total = 22.99m
                        },
                        new
                        {
                            Id = 2,
                            TimeStamp = new DateTime(2025, 8, 3, 14, 30, 48, 0, DateTimeKind.Unspecified),
                            Total = 61.20m
                        },
                        new
                        {
                            Id = 3,
                            TimeStamp = new DateTime(2025, 8, 7, 11, 39, 10, 0, DateTimeKind.Unspecified),
                            Total = 156.20m
                        },
                        new
                        {
                            Id = 4,
                            TimeStamp = new DateTime(2025, 8, 7, 19, 13, 55, 0, DateTimeKind.Unspecified),
                            Total = 107.50m
                        },
                        new
                        {
                            Id = 5,
                            TimeStamp = new DateTime(2025, 8, 8, 9, 4, 17, 0, DateTimeKind.Unspecified),
                            Total = 95.80m
                        });
                });

            modelBuilder.Entity("Ecommerce.Api.Models.LineItem", b =>
                {
                    b.HasOne("Ecommerce.Api.Models.Product", "Product")
                        .WithMany("LineItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Api.Models.Sale", "Sale")
                        .WithMany("LineItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Ecommerce.Api.Models.Product", b =>
                {
                    b.HasOne("Ecommerce.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ecommerce.Api.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Ecommerce.Api.Models.Product", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("Ecommerce.Api.Models.Sale", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
